apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-app-1
  template:
    metadata:
      labels:
        app: payment-app-1
    spec:
      containers:
        - name: payment-app-1
          image: example/payment-app-1:latest
---
apiVersion: v1
kind: Service
metadata:
  name: payment-app-1
spec:
  selector:
    app: payment-app-1
  ports:
    - port: 80
      targetPort: 8080
